[package]
name = "garden"
version = "0.1.0"
authors =["willyanfx"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
structopt = "0.3.25"

[dev-dependencies]
assert_cmd = "2.0.2"
